apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: task-tracker-back-end
  namespace: task-tracker
spec:
  interval: 1m
  releaseName: task-tracker-back-end
  chart:
    spec:
      chart: ./base/task-tracker-back-end
      sourceRef:
        kind: ExternalArtifact
        name: apps