apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway
  namespace: istio-system
spec:
  interval: 1m
  releaseName: gateway
  chart:
    spec:
      chart: ../../../infrastructure/base/gateway
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system