apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-tracker-front-end.fullname" . }}
  labels:
    {{- include "task-tracker-front-end.labels" . | nindent 4 }}
    istio.io/use-waypoint: "{{ .Values.service.istioUseWaypoint}}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-tracker-front-end.selectorLabels" . | nindent 4 }}
