apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-tracker-back-end.fullname" . }}
  labels:
    {{- include "task-tracker-back-end.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.properties: |
{{ .Files.Get "files/application.properties" | nindent 4 }}