apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-tracker-back-end.fullname" . }}
  labels:
    {{- include "task-tracker-back-end.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres